/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.net.MalformedURLException;

public class App   {

    public void getGreeting() throws InterruptedException, MalformedURLException {

             
        TestCases tests = new TestCases();
        
        //valid credentials
        tests.testCase01("Spoorti Ronad", "spoortironad93@gmail.com", "7411232212", "Assignment@2024");

        tests.testCase02("spoortironad20@gmail.com", "Itsmylife@2024");

        tests.testCase03();

        tests.testCase04();
        tests.testCase05();

        
        tests.endTests();

        
}

       

            
    
        
    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }

}